FHB-381 Fix warnings (combined)
DFE-Digital/fh-services pull request #116
Opened 2024-09-17 08:57 UTC by lazcool

2024-09-17 14:50 UTC, StuwiiDev approved these changes
Approving based on all changes being approved in other pull requests

2024-09-18 08:08 UTC, AaronJY requested changes
Only comment: can we add `<TreatWarningsAsErrors>True</TreatWarningsAsErrors>` to add to all csproj files? 🙌 They're missing on a few and it'd be good to enable this as standard across all of our projects

2024-09-18 08:08 UTC, AaronJY commented on src/service/notification-api/src/FamilyHubs.Notification.Api/FamilyHubs.Notification.Api.csproj
> +	<NuGetAuditMode>direct</NuGetAuditMode>
Can we add a `<TreatWarningsAsErrors>True</TreatWarningsAsErrors>` here?

2024-09-18 08:08 UTC, AaronJY commented on src/service/notification-api/src/FamilyHubs.Notification.Data/FamilyHubs.Notification.Data.csproj
> +		<NuGetAuditMode>direct</NuGetAuditMode>
Same here: `<TreatWarningsAsErrors>True</TreatWarningsAsErrors>`

2024-09-18 08:08 UTC, AaronJY commented on src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/FamilyHubs.Notification.UnitTests.csproj
> +	<NuGetAuditMode>direct</NuGetAuditMode>
`<TreatWarningsAsErrors>True</TreatWarningsAsErrors>`

2024-09-18 08:08 UTC, AaronJY commented on src/service/referral-api/acceptance-tests/FamilyHubs.Referral.Api.AcceptanceTests/FamilyHubs.Referral.Api.AcceptanceTests.csproj
> +	<NuGetAuditMode>direct</NuGetAuditMode>
`<TreatWarningsAsErrors>True</TreatWarningsAsErrors>`

2024-09-18 08:36 UTC, AaronJY submitted a review, later dismissed
<img src="https://media2.giphy.com/media/EJ9PTqxrBQHQI/giphy.gif"/>

2024-09-18 09:02 UTC, AaronJY approved these changes

2024-09-18 09:03 UTC, merged