FHB-736 : Notification API
DFE-Digital/fh-services pull request #157
Opened 2024-10-05 18:21 UTC by Zac-AND-Digital

Ticket: [FHB-736](https://dfedigital.atlassian.net/browse/FHB-736)

---

- Convert Moq -> NSubstitute for Notification API
- Refactor & Cleanup Code

[FHB-736]: https://dfedigital.atlassian.net/browse/FHB-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-07 15:25 UTC, stevesatdfe requested changes

2024-10-07 15:25 UTC, stevesatdfe commented on src/service/notification-api/tests/FamilyHubs.Notification.UnitTests/WhenGettingSentNotifications.cs
> +        result.Items.Count.Should().Be(apiKeyType is not null ? 1 : 2);
Maybe pass the 1 or 2 in with the parameter for apiKeyType

2024-10-07 15:34 UTC, stevesatdfe approved these changes

2024-10-08 09:27 UTC, AaronJY approved these changes

2024-10-08 10:20 UTC, merged