Switch shared razor to package reference. Move health check code to s…
DFE-Digital/fh-services pull request #203
Opened 2024-10-24 15:25 UTC by Top-Cat

…hared kernel (non-razor)

2024-10-25 15:10 UTC, stevesatdfe approved these changes

2024-10-28 10:29 UTC, AaronJY requested changes
LGTM! Please can you add an entry to the `util/README.md` file on what `npm-install.sh` does and what it's used for?

2024-10-28 10:52 UTC, Zac-Digital approved these changes

2024-10-28 12:23 UTC, AaronJY approved these changes

2024-10-28 13:06 UTC, Zac-Digital approved these changes

2024-10-28 13:48 UTC, merged